name: .NET CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.2.2
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v4
      id: semantic
      with:
        dry_run: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Set Build Version
      id: version
      run: |
        if [ -z $SEM_VER ]
        then
          echo "num=1.0.0" >> $GITHUB_OUTPUT
        else
          echo "num="$SEM_VER >> $GITHUB_OUTPUT
        fi
      env:
        SEM_VER: ${{ steps.semantic.outputs.new_release_version }}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -p:VersionPrefix=${{ steps.version.outputs.num }}
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Upload nupkg
      uses: actions/upload-artifact@v4.6.1
      with:
        name: nuget
        path: nugets/*.nupkg
        retention-days: 5
    - name: Semantic Release Tag
      uses: cycjimmy/semantic-release-action@v4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
